# Generated by Django 5.2 on 2025-04-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='conferences.conference')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='doctors.doctor')),
            ],
            options={
                'ordering': ['conference__start_date'],
                'unique_together': {('conference', 'doctor')},
            },
        ),
    ]
