# Generated by Django 5.2 on 2025-04-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['year', 'conference__title']},
        ),
        migrations.RemoveField(
            model_name='cost',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cost',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
