# Generated by Django 5.2 on 2025-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_cost_options_remove_cost_created_at_cost_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
