# Generated by Django 5.2 on 2025-04-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_alter_cost_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['conference__start_date', 'conference__title']},
        ),
        migrations.RemoveField(
            model_name='cost',
            name='year',
        ),
    ]
